#!/usr/bin/env bash

set -m 

dashfile='Dashfile'
limit=5
QUEUE=()

stopworkers() {
    for id in ${QUEUE[@]}; do
        if ps $id > /dev/null ; then
            kill -TERM $id
            echo "stop pid $id"
        fi
    done
    exit 1
}

trap 'stopworkers' INT

enqueue() {
    QUEUE=("${QUEUE[@]}" $1)
    #echo "enqueue: ${QUEUE[@]}"
}


dequeue() {
    OLDQUEUE=${QUEUE[@]}
    QUEUE=()
    for id in ${OLDQUEUE[@]}; do
        if [ ! $id -eq $1 ]; then
            QUEUE=("${QUEUE[@]}" $id)
        fi
    done
    #echo "dequeue: ${QUEUE[@]}"
}


checkworkers() {
    OLDQUEUE=${QUEUE[@]}
    #echo "checkworkers: ${QUEUE[@]}"
    for id in ${OLDQUEUE[@]}; do
        if ! ps $id > /dev/null ; then
            dequeue $id
        fi
    done
}


[[ -n "$1" ]] && limit=$1

while read line; do
    [[ -z "$line" ]] && continue
    echo "$line" | grep "^\s*\#" > /dev/null && continue

    while [ ${#QUEUE[@]} -ge $limit ]; do 
        checkworkers; continue;
    done

    $line &
    enqueue $!
    echo "$(date +%T) | started with pid $!: $line"
done < $dashfile

for id in ${QUEUE[@]}; do 
    wait $id
done

echo "... finished"